//! Cisco ASA Extended ACL format generator.

use std::collections::HashMap;

use crate::{EnforcementConfig, EnforcementFormat, Zone, ZonePairPolicy};

use super::{build_acl_name, sanitize_acl_name, zone_name};
use super::vendor_context::vendor_remark_for_rule;
use super::protocol_to_transport;

/// Cisco ASA Extended ACL format.
///
/// Zones with more than 3 assets use `object-group network` entries.
/// Smaller zones fall back to `any`.
pub(super) fn gen_cisco_asa(
    pairs: &[ZonePairPolicy],
    zone_names: &HashMap<String, String>,
    zones: &[Zone],
    zone_vendors: &HashMap<String, Vec<String>>,
) -> EnforcementConfig {
    let zone_by_id: HashMap<&str, &Zone> = zones.iter().map(|z| (z.id.as_str(), z)).collect();

    let mut out = String::new();
    out.push_str("! Generated by Kusanagi Kajiki microsegmentation analysis\n");
    out.push_str("! Format: Cisco ASA Extended ACL\n");
    out.push_str(
        "! Note: Populate object-group members with actual IP addresses before deployment.\n",
    );
    out.push_str("!\n");

    let mut rule_count = 0usize;

    // Collect unique zone IDs referenced by any pair (preserving first-seen order).
    let mut zone_ids_seen: Vec<&str> = Vec::new();
    for pair in pairs {
        for zid in [pair.src_zone_id.as_str(), pair.dst_zone_id.as_str()] {
            if !zone_ids_seen.contains(&zid) {
                zone_ids_seen.push(zid);
            }
        }
    }

    // Emit object-groups for zones with more than 3 assets.
    for &zone_id in &zone_ids_seen {
        let asset_count = zone_by_id.get(zone_id).map(|z| z.asset_count).unwrap_or(0);
        if asset_count > 3 {
            let name = zone_names
                .get(zone_id)
                .map(|s| s.as_str())
                .unwrap_or(zone_id);
            let obj_name: String = format!("OBJ-{}", sanitize_acl_name(name))
                .chars()
                .take(64)
                .collect();
            out.push_str(&format!("object-group network {obj_name}\n"));
            out.push_str(&format!(
                " description {name} ({asset_count} assets - add member ip entries)\n"
            ));
            out.push_str("!\n");
        }
    }

    // Emit ACL rules per zone pair.
    for pair in pairs {
        let src_name = zone_name(zone_names, &pair.src_zone_id);
        let dst_name = zone_name(zone_names, &pair.dst_zone_id);
        let acl_name = build_acl_name(src_name, dst_name);

        let src_assets = zone_by_id
            .get(pair.src_zone_id.as_str())
            .map(|z| z.asset_count)
            .unwrap_or(0);
        let dst_assets = zone_by_id
            .get(pair.dst_zone_id.as_str())
            .map(|z| z.asset_count)
            .unwrap_or(0);

        let src_san: String = sanitize_acl_name(src_name).chars().take(28).collect();
        let dst_san: String = sanitize_acl_name(dst_name).chars().take(28).collect();

        let src_clause = if src_assets > 3 {
            format!("object-group OBJ-{src_san}")
        } else {
            "any".to_string()
        };
        let dst_clause = if dst_assets > 3 {
            format!("object-group OBJ-{dst_san}")
        } else {
            "any".to_string()
        };

        out.push_str(&format!("! Zone pair: {src_name} → {dst_name}\n"));

        for rule in &pair.rules {
            let transport = protocol_to_transport(&rule.protocol, rule.dst_port);

            // Vendor-aware remark.
            if let Some(vendor_ctx) = vendor_remark_for_rule(
                zone_vendors,
                &pair.src_zone_id,
                &pair.dst_zone_id,
                rule.dst_port,
            ) {
                out.push_str(&format!("! {vendor_ctx}\n"));
            }

            if let Some(port) = rule.dst_port {
                out.push_str(&format!(
                    "access-list {acl_name} extended permit {transport} \
                     {src_clause} {dst_clause} eq {port}\n"
                ));
            } else {
                out.push_str(&format!(
                    "access-list {acl_name} extended permit {transport} \
                     {src_clause} {dst_clause}\n"
                ));
            }
            rule_count += 1;
        }

        out.push_str(&format!(
            "access-list {acl_name} extended deny ip any any log\n"
        ));
        out.push_str(&format!("access-group {acl_name} in interface <outside>\n"));
        out.push_str("!\n");
    }

    if pairs.is_empty() {
        out.push_str("! No zone pairs defined.\n");
    }

    EnforcementConfig::new(EnforcementFormat::CiscoAsaAcl, out, rule_count)
}
