//! Cisco IOS Extended ACL format generator.

use std::collections::HashMap;

use crate::{EnforcementConfig, EnforcementFormat, ZonePairPolicy};

use super::{build_acl_name, zone_name};
use super::vendor_context::vendor_remark_for_rule;
use super::protocol_to_transport;

/// Cisco IOS Extended ACL format.
///
/// One ACL per zone pair, named `ACL-{SRC}-TO-{DST}` (sanitized, max 64 chars).
/// Emits `permit` lines for each rule and a `deny ip any any log` trailer.
pub(super) fn gen_cisco_ios(
    pairs: &[ZonePairPolicy],
    zone_names: &HashMap<String, String>,
    zone_vendors: &HashMap<String, Vec<String>>,
) -> EnforcementConfig {
    let mut out = String::new();
    out.push_str("! Generated by Kusanagi Kajiki microsegmentation analysis\n");
    out.push_str("! Format: Cisco IOS Extended ACL\n");
    out.push_str("! Note: Replace 'any' with actual IP ranges/subnets before deployment.\n");
    out.push_str("!\n");

    let mut rule_count = 0usize;

    for pair in pairs {
        let src_name = zone_name(zone_names, &pair.src_zone_id);
        let dst_name = zone_name(zone_names, &pair.dst_zone_id);
        let acl_name = build_acl_name(src_name, dst_name);

        out.push_str(&format!("ip access-list extended {acl_name}\n"));
        out.push_str(&format!(" ! Remark: {src_name} → {dst_name}\n"));

        for rule in &pair.rules {
            let transport = protocol_to_transport(&rule.protocol, rule.dst_port);
            let risk_str = format!("{:?}", rule.risk).to_lowercase();

            // Vendor-aware remark (e.g., "Siemens — S7comm PLC communication").
            if let Some(vendor_ctx) = vendor_remark_for_rule(
                zone_vendors,
                &pair.src_zone_id,
                &pair.dst_zone_id,
                rule.dst_port,
            ) {
                out.push_str(&format!(" ! Remark: {vendor_ctx}\n"));
            }

            // Truncate justification to fit within IOS remark line limit.
            let just: String = rule.justification.chars().take(80).collect();
            out.push_str(&format!(" ! Remark: [{risk_str}] {just}\n"));
            if let Some(port) = rule.dst_port {
                out.push_str(&format!(" permit {transport} any any eq {port}\n"));
            } else {
                out.push_str(&format!(" permit {transport} any any\n"));
            }
            rule_count += 1;
        }

        out.push_str(" deny ip any any log\n");
        out.push_str("!\n");
    }

    if pairs.is_empty() {
        out.push_str("! No zone pairs defined — default deny applies to all traffic.\n");
        out.push_str("!\n");
    }

    EnforcementConfig::new(EnforcementFormat::CiscoIosAcl, out, rule_count)
}
