//! Suricata IDS/IPS rules format generator.

use std::collections::HashMap;

use crate::{EnforcementConfig, EnforcementFormat, ZonePairPolicy};

use super::{sanitize_suricata_msg, zone_name};
use super::vendor_context::vendor_remark_for_rule;
use super::protocol_to_transport;

/// Suricata IDS/IPS rules — `pass`/`drop` syntax with SIDs starting at 9000001.
pub(super) fn gen_suricata(
    pairs: &[ZonePairPolicy],
    zone_names: &HashMap<String, String>,
    zone_vendors: &HashMap<String, Vec<String>>,
) -> EnforcementConfig {
    let mut out = String::new();
    out.push_str("# Generated by Kusanagi Kajiki microsegmentation analysis\n");
    out.push_str("# Format: Suricata IDS/IPS rules\n");
    out.push_str("# Place in /etc/suricata/rules/knk-policy.rules and enable in suricata.yaml\n");
    out.push_str("#\n");

    let mut sid: u32 = 9_000_001;
    let mut rule_count = 0usize;

    for pair in pairs {
        let src_name = zone_name(zone_names, &pair.src_zone_id);
        let dst_name = zone_name(zone_names, &pair.dst_zone_id);

        out.push_str(&format!("# Zone pair: {src_name} → {dst_name}\n"));

        for rule in &pair.rules {
            let transport = protocol_to_transport(&rule.protocol, rule.dst_port);
            let port_str = rule
                .dst_port
                .map(|p| p.to_string())
                .unwrap_or_else(|| "any".to_string());
            let risk_str = format!("{:?}", rule.risk).to_lowercase();

            // Include vendor context in msg if available.
            let vendor_suffix = vendor_remark_for_rule(
                zone_vendors,
                &pair.src_zone_id,
                &pair.dst_zone_id,
                rule.dst_port,
            )
            .map(|ctx| format!(" ({ctx})"))
            .unwrap_or_default();

            let msg = sanitize_suricata_msg(&format!(
                "KNK-ALLOW: {}/{} {} to {} [{}]{}",
                rule.protocol, port_str, src_name, dst_name, risk_str, vendor_suffix
            ));

            out.push_str(&format!(
                "pass {transport} any any -> any {port_str} \
                 (msg:\"{msg}\"; sid:{sid}; rev:1;)\n"
            ));
            sid += 1;
            rule_count += 1;
        }
    }

    // Default drop rule — catches everything not explicitly passed above.
    out.push_str("#\n");
    out.push_str(&format!(
        "drop ip any any -> any any \
         (msg:\"KNK-DENY: No conduit - default deny all unmatched traffic\"; sid:{sid}; rev:1;)\n"
    ));

    EnforcementConfig::new(EnforcementFormat::SuricataRules, out, rule_count)
}
